name: McMasterful Books Backend CI

on: 
  push: 
  pull_request:

jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'           
      - run: npm install
      - run: npm run lint
    
  check_types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'           
      - run: npm install
      - run: npm run check-types

  generate_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - name: Generate OpenAPI Routes and Client
        run: |
          npx tsoa spec-and-routes
          npx @openapitools/openapi-generator-cli generate -i ./dist/swagger.json -o ./client -g typescript-fetch
      - name: Store Client as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: client-sdk
          path: client

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'           
      - run: npm install
      - run: npm run test:ci
